//! Native `WinUI` 3 backend for `WaterUI`.
//!
//! This crate projects `WaterUI` views onto Windows App SDK (`WinUI` 3) controls.
//! It does not use a virtual tree or a reconciler: a [`ViewDispatcher`] maps
//! each view to a concrete `Microsoft.UI.Xaml` element once, and `nami`
//! watchers drive per-property updates directly on the live element.
//!
//! The crate only compiles its API surface on Windows; on other targets it is
//! empty so downstream crates can depend on it unconditionally.

#![cfg(target_os = "windows")]

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::cargo,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    reason = "generated by windows-bindgen from the WASDK winmd; regenerated, never hand-edited"
)]
pub(crate) mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub(crate) mod app_shim;
/// Handler constructors for `WinRT` events raised off the `UI` thread.
///
/// A handler built by `background_handler` must be `Send + Sync`, so one that
/// captures `UI`-thread state does not compile:
///
/// ```compile_fail,E0277
/// mod background_events {
///     include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/background_events.rs"));
/// }
/// use windows_core::IInspectable;
///
/// let state = std::rc::Rc::new(std::cell::Cell::new(0_u32));
/// let _handler = background_events::background_handler::<IInspectable, IInspectable>(
///     move |_, _| state.set(state.get() + 1),
/// );
/// ```
///
/// Capturing only a channel sender — how the media coordinator hands event
/// data to the `UI` thread — does:
///
/// ```
/// mod background_events {
///     include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/background_events.rs"));
/// }
/// use windows_core::IInspectable;
///
/// let (sender, _receiver) = async_channel::unbounded::<u32>();
/// let _handler = background_events::background_handler::<IInspectable, IInspectable>(
///     move |_, _| {
///         let _ = sender.try_send(1);
///     },
/// );
/// ```
mod background_events;
pub(crate) mod bootstrap;
pub(crate) mod component;
pub(crate) mod components;
// `#[implement]` generates `IUnknown` helpers clippy's pedantic group flags.
#[allow(clippy::inline_always, clippy::ref_as_ptr)]
pub(crate) mod d2d;
pub(crate) mod executor;
#[cfg(feature = "gpu")]
pub(crate) mod gpu;
pub(crate) mod key_input;
pub(crate) mod layout;
pub(crate) mod renderer;
pub(crate) mod session_end;
pub(crate) mod theme;
pub(crate) mod util;
pub(crate) mod window;

mod app;

pub use app::run_app;
pub use component::WinUiComponent;
pub use renderer::WinUiRenderer;
