//! Native WinUI 3 backend for `WaterUI`.
//!
//! This crate projects `WaterUI` views onto Windows App SDK (WinUI 3) controls.
//! It does not use a virtual tree or a reconciler: a [`ViewDispatcher`] maps
//! each view to a concrete `Microsoft.UI.Xaml` element once, and `nami`
//! watchers drive per-property updates directly on the live element.
//!
//! The crate only compiles its API surface on Windows; on other targets it is
//! empty so downstream crates can depend on it unconditionally.

#![cfg(target_os = "windows")]

#[allow(
    clippy::missing_transmute_annotations,
    clippy::upper_case_acronyms,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    reason = "generated by windows-bindgen from the WASDK winmd; regenerated, never hand-edited"
)]
pub(crate) mod bindings;

pub(crate) mod app_shim;
pub(crate) mod bootstrap;
pub(crate) mod component;
pub(crate) mod components;
pub(crate) mod executor;
#[cfg(feature = "gpu")]
pub(crate) mod gpu;
pub(crate) mod layout;
pub(crate) mod renderer;
pub(crate) mod util;
pub(crate) mod window;

mod app;

pub use app::run_app;
pub use component::WinUiComponent;
pub use renderer::WinUiRenderer;
